AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-init-template-runtime-go
  
  Sample SAM Template for sam-init-template-runtime-go

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./build/bin/
      Handler: sam-init-template-runtime-go
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sam-init-template-runtime-go
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE

  CurrentTimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/bin/
      Handler: current-time
      Runtime: go1.x
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /current-time
            Method: GET

  HelloUsernameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/bin/
      Handler: hello-username
      Runtime: go1.x
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /hello-username
            Method: GET

  RetrieveCompaniesDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/bin/
      Handler: retrieve-companies-data
      Runtime: go1.x
      Events:
        CompaniesDataCSVFileUploaded:
          Type: S3
          Properties:
            Bucket: !Ref CompaniesDataBucket
            Events: s3:ObjectCreated:*
      Environment:
        Variables:
          CompaniesDataTableName: CompaniesData

  CompaniesDataBucket:
    Type: AWS::S3::Bucket

  CompaniesDataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: CompaniesDataBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt RetrieveCompaniesDataFunctionRole.Arn
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref CompaniesDataBucket
                - /*
      Bucket: !Ref CompaniesDataBucket

  CompaniesDataDynamoDBTable:
    TableName: CompaniesData
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        AppType: Serverless
        Awesome: TrueTrue
      SSESpecification:
        SSEEnabled: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api

  HelloWorldAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn

  CurrentTimeAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/current-time/"
  CurrentTimeFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt CurrentTimeFunction.Arn
  CurrentTimeFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CurrentTimeFunctionRole.Arn

  HelloUsernameAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello-username/"
  HelloUsernameFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HelloUsernameFunction.Arn
  HelloUsernameFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloUsernameFunctionRole.Arn

  RetrieveCompaniesDataFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt RetrieveCompaniesDataFunction.Arn
  RetrieveCompaniesDataFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt RetrieveCompaniesDataFunctionRole.Arn

Metadata:
  AWS::ServerlessRepo::Application:
    Name: sam-init-template-runtime-go
    Description: hello world
    Author: GFB
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: ['tests']
    HomePageUrl: https://github.com/goforbroke1006/sam-init-template-runtime-go
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/goforbroke1006/sam-init-template-runtime-go
